name:                coinBot
version:             0.1.0.0
github:              "jeorp/coinBot"
license:             BSD3
author:              "jerop"
maintainer:          "jeorp@google.com"
copyright:           "2021 jeorp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/coinBot#readme>

dependencies:
- base >= 4.7 && < 5
- text
- transformers
- directory
- mtl
- text
- vector
- unliftio
- discord-haskell
- cassava
- aeson
- aeson-qq
- lens-aeson
- extensible
- binary
- bytestring
- base16-bytestring
- cryptohash-sha256
- time
- safe-exceptions
- lens
- data-default-class
- attoparsec
- websockets
- http-client
- http-conduit
- wuss
- network
- sqlite-simple
- hedis
- amqp
- Chart
- Chart-cairo
- Chart-diagrams
- Chart-gtk
- colour
- hspec
- QuickCheck
library:
  source-dirs: src

executables:
  coinBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coinBot

tests:
  coinBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coinBot
