
resolver: lts-18.16

extra-deps:
- emoji-0.1.0.2
- discord-haskell-1.8.9
- aeson-2.0.2.0
- lens-aeson-1.1.3
- OneTuple-0.3.1
- extensible-0.8.3
- incremental-0.3.1
- membership-0.0.1
- semialign-1.2.0.1
- redis-0.14.2
