
resolver: lts-18.16

extra-deps:
- emoji-0.1.0.2
- discord-haskell-1.8.9
- aeson-2.0.2.0
- lens-aeson-1.1.3
- OneTuple-0.3.1
- extensible-0.8.3
- incremental-0.3.1
- membership-0.0.1
- semialign-1.2.0.1
- redis-0.14.2
- Chart-cairo-1.9.3
- cairo-0.13.8.1
- gtk2hs-buildtools-0.13.8.2
- Chart-diagrams-1.9.3
- Chart-gtk-1.9.3
- SVGFonts-1.7.0.1
- diagrams-core-1.5.0
- diagrams-lib-1.4.4
- diagrams-postscript-1.5
- diagrams-svg-1.4.3
- gtk-0.15.5
- svg-builder-0.1.1
- dual-tree-0.2.3.0
- gio-0.13.8.1
- glib-0.13.8.1
- monoid-extras-0.6.1
- pango-0.13.8.1
- statestack-0.3
- active-0.2.0.15